title: Tapia 2019 Doctoral Consortium
show_downloads: false


description: "<small>
<b>Lunch:</b> 12p - 1p  <br/>
<br/>
<b>Opening/Intro:</b> 1p - 1:15p <br/>
<b>Session 1:</b> 1:15p - 1:45p <br/>
<b>Session 2:</b> 1:45p - 2:15p <br/>
<br/>
<b>Coffee Break</b> <br/>
<br/>
<b>Session 3:</b> 2:30p - 3:00p <br/>
<b>Session 4:</b> 3:00p - 3:30p <br/>
<br/>
<b>Break</b> <br/>
<br/>
<b>Session 5:</b> 3:45p - 4:15p <br/>
<b>Session 6:</b> 4:15p - 4:45p <br/>
<b>Closing:</b> 4:45p - 5:00p <br/>
<br/> 
<b>Networking (optional)</b> <br/>
<br/>
</small>"


theme: jekyll-theme-minimal
